import * as fs from 'node:fs';
import * as path from 'node:path';
import { createLogger } from '@consuelo/logger';

const logger = createLogger('CLI:Docker');

const DOCKER_COMPOSE_TEMPLATE = `# OpenSaaS - Self-hosted deployment
# Generated by: npx @consuelo/cli init
# Usage: docker-compose up -d

services:
  postgres:
    image: postgres:15-alpine
    container_name: opensaas-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: \${DB_USER:-opensaas}
      POSTGRES_PASSWORD: \${DB_PASSWORD:?Set DB_PASSWORD in .env}
      POSTGRES_DB: \${DB_NAME:-opensaas}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "\${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${DB_USER:-opensaas}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - opensaas

  twenty:
    image: twentycrm/twenty:latest
    container_name: opensaas-crm
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://\${DB_USER:-opensaas}:\${DB_PASSWORD}@postgres:5432/\${DB_NAME:-opensaas}
      FRONT_BASE_URL: \${TWENTY_URL:-http://localhost:3000}
    ports:
      - "\${TWENTY_PORT:-3000}:3000"
    networks:
      - opensaas

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opensaas-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://\${DB_USER:-opensaas}:\${DB_PASSWORD}@postgres:5432/\${DB_NAME:-opensaas}
      TWILIO_ACCOUNT_SID: \${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: \${TWILIO_AUTH_TOKEN}
      GROQ_API_KEY: \${GROQ_API_KEY}
      CLERK_SECRET_KEY: \${CLERK_SECRET_KEY:-}
      WHISPER_MODEL_PATH: \${WHISPER_MODEL_PATH:-}
    ports:
      - "\${API_PORT:-8000}:8000"
    networks:
      - opensaas

volumes:
  postgres_data:
    name: opensaas-postgres-data

networks:
  opensaas:
    name: opensaas-network
`;

const ENV_EXAMPLE_TEMPLATE = `# OpenSaaS Environment Configuration
# Copy to .env and fill in your values

# Database
DB_USER=opensaas
DB_PASSWORD=          # Required: Set a secure password
DB_NAME=opensaas
DB_PORT=5432

# Service Ports
TWENTY_PORT=3000
TWENTY_URL=http://localhost:3000
API_PORT=8000

# Twilio (for dialer)
TWILIO_ACCOUNT_SID=   # Required: Your Twilio Account SID (starts with AC)
TWILIO_AUTH_TOKEN=    # Required: Your Twilio Auth Token
TWILIO_PHONE_NUMBER=  # Required: E.164 format (+1234567890)

# Groq (for AI coaching)
GROQ_API_KEY=         # Required: Your Groq API key (starts with gsk_)

# Clerk (for authentication - optional)
CLERK_SECRET_KEY=     # Optional: Your Clerk secret key

# Local STT (optional)
WHISPER_MODEL_PATH=   # Optional: Path to local whisper model
`;

export function generateDockerCompose(outputDir: string = process.cwd()): void {
  const composePath = path.join(outputDir, 'docker-compose.yml');
  const envExamplePath = path.join(outputDir, '.env.example');

  for (const filePath of [composePath, envExamplePath]) {
    if (fs.existsSync(filePath)) {
      logger.warn(`  ⚠ Overwriting existing ${path.basename(filePath)}`);
    }
  }

  fs.writeFileSync(composePath, DOCKER_COMPOSE_TEMPLATE);
  fs.writeFileSync(envExamplePath, ENV_EXAMPLE_TEMPLATE);

  logger.info('\nGenerated:');
  logger.info('  - docker-compose.yml');
  logger.info('  - .env.example');
}
