/*
 * _____                    _
 *|_   _|_      _____ _ __ | |_ _   _
 *  | | \ \ /\ / / _ \ '_ \| __| | | | Auto-generated file
 *  | |  \ V  V /  __/ | | | |_| |_| | DO NOT EDIT - changes will be overwritten
 *  |_|   \_/\_/ \___|_| |_|\__|\__, | Generated by: yarn docs:generate-paths
 *                              |___/
 *
 * This file is generated from packages/consuelo-docs/navigation/base-structure.json
 * To add new documentation pages, add them to base-structure.json and run:
 *   yarn docs:generate-paths
 */

export const DOCUMENTATION_PATHS = {
  CONSUELO_UI_DISPLAY_APP_TOOLTIP: '/consuelo-ui/display/app-tooltip',
  CONSUELO_UI_DISPLAY_CHECKMARK: '/consuelo-ui/display/checkmark',
  CONSUELO_UI_DISPLAY_CHIP: '/consuelo-ui/display/chip',
  CONSUELO_UI_DISPLAY_ICONS: '/consuelo-ui/display/icons',
  CONSUELO_UI_DISPLAY_SOON_PILL: '/consuelo-ui/display/soon-pill',
  CONSUELO_UI_DISPLAY_TAG: '/consuelo-ui/display/tag',
  CONSUELO_UI_INPUT_BLOCK_EDITOR: '/consuelo-ui/input/block-editor',
  CONSUELO_UI_INPUT_BUTTONS: '/consuelo-ui/input/buttons',
  CONSUELO_UI_INPUT_CHECKBOX: '/consuelo-ui/input/checkbox',
  CONSUELO_UI_INPUT_COLOR_SCHEME: '/consuelo-ui/input/color-scheme',
  CONSUELO_UI_INPUT_ICON_PICKER: '/consuelo-ui/input/icon-picker',
  CONSUELO_UI_INPUT_IMAGE_INPUT: '/consuelo-ui/input/image-input',
  CONSUELO_UI_INPUT_RADIO: '/consuelo-ui/input/radio',
  CONSUELO_UI_INPUT_SELECT: '/consuelo-ui/input/select',
  CONSUELO_UI_INPUT_TEXT: '/consuelo-ui/input/text',
  CONSUELO_UI_INPUT_TOGGLE: '/consuelo-ui/input/toggle',
  CONSUELO_UI_INTRODUCTION: '/consuelo-ui/introduction',
  CONSUELO_UI_NAVIGATION: '/consuelo-ui/navigation',
  CONSUELO_UI_NAVIGATION_BREADCRUMB: '/consuelo-ui/navigation/breadcrumb',
  CONSUELO_UI_NAVIGATION_LINKS: '/consuelo-ui/navigation/links',
  CONSUELO_UI_NAVIGATION_MENU_ITEM: '/consuelo-ui/navigation/menu-item',
  CONSUELO_UI_NAVIGATION_NAVIGATION_BAR:
    '/consuelo-ui/navigation/navigation-bar',
  CONSUELO_UI_NAVIGATION_STEP_BAR: '/consuelo-ui/navigation/step-bar',
  CONSUELO_UI_PROGRESS_BAR: '/consuelo-ui/progress-bar',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_BACKEND_DEVELOPMENT_BEST_PRACTICES_SERVER:
    '/developers/contribute/capabilities/backend-development/best-practices-server',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_BACKEND_DEVELOPMENT_CUSTOM_OBJECTS:
    '/developers/contribute/capabilities/backend-development/custom-objects',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_BACKEND_DEVELOPMENT_FEATURE_FLAGS:
    '/developers/contribute/capabilities/backend-development/feature-flags',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_BACKEND_DEVELOPMENT_FOLDER_ARCHITECTURE_SERVER:
    '/developers/contribute/capabilities/backend-development/folder-architecture-server',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_BACKEND_DEVELOPMENT_QUEUE:
    '/developers/contribute/capabilities/backend-development/queue',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_BACKEND_DEVELOPMENT_SERVER_COMMANDS:
    '/developers/contribute/capabilities/backend-development/server-commands',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_BACKEND_DEVELOPMENT_ZAPIER:
    '/developers/contribute/capabilities/backend-development/zapier',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_BUG_AND_REQUESTS:
    '/developers/contribute/capabilities/bug-and-requests',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_FRONTEND_DEVELOPMENT_BEST_PRACTICES_FRONT:
    '/developers/contribute/capabilities/frontend-development/best-practices-front',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_FRONTEND_DEVELOPMENT_FOLDER_ARCHITECTURE_FRONT:
    '/developers/contribute/capabilities/frontend-development/folder-architecture-front',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_FRONTEND_DEVELOPMENT_FRONTEND_COMMANDS:
    '/developers/contribute/capabilities/frontend-development/frontend-commands',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_FRONTEND_DEVELOPMENT_HOTKEYS:
    '/developers/contribute/capabilities/frontend-development/hotkeys',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_FRONTEND_DEVELOPMENT_STORYBOOK:
    '/developers/contribute/capabilities/frontend-development/storybook',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_FRONTEND_DEVELOPMENT_STYLE_GUIDE:
    '/developers/contribute/capabilities/frontend-development/style-guide',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_FRONTEND_DEVELOPMENT_WORK_WITH_FIGMA:
    '/developers/contribute/capabilities/frontend-development/work-with-figma',
  DEVELOPERS_CONTRIBUTE_CAPABILITIES_LOCAL_SETUP:
    '/developers/contribute/capabilities/local-setup',
  DEVELOPERS_CONTRIBUTE_CONTRIBUTE: '/developers/contribute/contribute',
  DEVELOPERS_EXTEND_CAPABILITIES_APIS: '/developers/extend/capabilities/apis',
  DEVELOPERS_EXTEND_CAPABILITIES_APPS: '/developers/extend/capabilities/apps',
  DEVELOPERS_EXTEND_CAPABILITIES_WEBHOOKS:
    '/developers/extend/capabilities/webhooks',
  DEVELOPERS_EXTEND_EXTEND: '/developers/extend/extend',
  DEVELOPERS_INTRODUCTION: '/developers/introduction',
  DEVELOPERS_SELF_HOST_CAPABILITIES_CLOUD_PROVIDERS:
    '/developers/self-host/capabilities/cloud-providers',
  DEVELOPERS_SELF_HOST_CAPABILITIES_DOCKER_COMPOSE:
    '/developers/self-host/capabilities/docker-compose',
  DEVELOPERS_SELF_HOST_CAPABILITIES_SETUP:
    '/developers/self-host/capabilities/setup',
  DEVELOPERS_SELF_HOST_CAPABILITIES_TROUBLESHOOTING:
    '/developers/self-host/capabilities/troubleshooting',
  DEVELOPERS_SELF_HOST_CAPABILITIES_UPGRADE_GUIDE:
    '/developers/self-host/capabilities/upgrade-guide',
  DEVELOPERS_SELF_HOST_SELF_HOST: '/developers/self-host/self-host',
  GRAPHQL_API_ANALYTICS_CONNECTING_EXTERNAL_ANALYTICS:
    '/graphql-api/analytics/connecting-external-analytics',
  GRAPHQL_API_ANALYTICS_GROWTH_METRICS_DASHBOARDS:
    '/graphql-api/analytics/growth-metrics-dashboards',
  GRAPHQL_API_ANALYTICS_SCHEDULED_REPORTS:
    '/graphql-api/analytics/scheduled-reports',
  GRAPHQL_API_AUTOMATION_DATA_CLEANUP_AUTOMATION:
    '/graphql-api/automation/data-cleanup-automation',
  GRAPHQL_API_AUTOMATION_INTERNAL_WORKFLOWS_OVERVIEW:
    '/graphql-api/automation/internal-workflows-overview',
  GRAPHQL_API_AUTOMATION_LEAD_SCORING_SETUP:
    '/graphql-api/automation/lead-scoring-setup',
  GRAPHQL_API_AUTOMATION_SLACK_NOTIFICATIONS:
    '/graphql-api/automation/slack-notifications',
  GRAPHQL_API_GENERAL_BULK_UPDATE_SCRIPT:
    '/graphql-api/general/bulk-update-script',
  GRAPHQL_API_GENERAL_EXPORT_ANALYTICS: '/graphql-api/general/export-analytics',
  GRAPHQL_API_GENERAL_IMPORT_AUTOMATION:
    '/graphql-api/general/import-automation',
  GRAPHQL_API_GENERAL_INTERNAL_API_ACCESS:
    '/graphql-api/general/internal-api-access',
  GRAPHQL_API_GENERAL_RATE_LIMITS_AND_BEST_PRACTICES:
    '/graphql-api/general/rate-limits-and-best-practices',
  GRAPHQL_API_GETTING_STARTED_SETTING_UP_INTERNAL_WORKSPACE:
    '/graphql-api/getting-started/setting-up-internal-workspace',
  GRAPHQL_API_OVERVIEW: '/graphql-api/overview',
  GRAPHQL_API_TROUBLESHOOTING_COMMON_OPS_ISSUES:
    '/graphql-api/troubleshooting/common-ops-issues',
  OS_AGENT_CONTEXT_DECISION: '/os/agent-context/decision',
  OS_AGENT_CONTEXT_SCRIPTS: '/os/agent-context/scripts',
  OS_AGENT_CONTEXT_STEERING: '/os/agent-context/steering',
  OS_AGENT_CONTEXT_TEST_DRIVEN_AGENT_WORK:
    '/os/agent-context/test-driven-agent-work',
  OS_AGENT_CONTEXT_TOOLS: '/os/agent-context/tools',
  OS_CONCEPTS_APPROVALS: '/os/concepts/approvals',
  OS_CONCEPTS_CONTEXT_AND_MEMORY: '/os/concepts/context-and-memory',
  OS_CONCEPTS_DATA_MODEL_AND_GRAPHQL: '/os/concepts/data-model-and-graphql',
  OS_CONCEPTS_FILES_AND_ARTIFACTS: '/os/concepts/files-and-artifacts',
  OS_CONCEPTS_INTEGRATIONS_AND_CAPABILITIES:
    '/os/concepts/integrations-and-capabilities',
  OS_CONCEPTS_LOCAL_AND_CLOUD: '/os/concepts/local-and-cloud',
  OS_CONCEPTS_OBSERVABILITY: '/os/concepts/observability',
  OS_CONCEPTS_PORTAL: '/os/concepts/portal',
  OS_CONCEPTS_SCRIPTS: '/os/concepts/scripts',
  OS_CONCEPTS_SKILLS: '/os/concepts/skills',
  OS_GLOSSARY: '/os/glossary',
  OS_HOW_IT_WORKS: '/os/how-it-works',
  OS_OVERVIEW: '/os/overview',
  OS_SKILLS_BROWSER: '/os/skills/browser',
  OS_SKILLS_CONSUELO_DESIGN: '/os/skills/consuelo-design',
  OS_SKILLS_CONSUELO_DESIGN_LANDING_PAGE:
    '/os/skills/consuelo-design-landing-page',
  OS_SKILLS_CONSUELO_WORKSPACE_SNAPSHOT:
    '/os/skills/consuelo-workspace-snapshot',
  OS_SKILLS_DAILY_REVENUE_BRIEF: '/os/skills/daily-revenue-brief',
  OS_SKILLS_DEBUGGER: '/os/skills/debugger',
  OS_SKILLS_HANDOFF: '/os/skills/handoff',
  OS_SKILLS_PLANNED_CAMPAIGN_BRIEF: '/os/skills/planned/campaign-brief',
  OS_SKILLS_PLANNED_FOLLOW_UP_GENERATOR:
    '/os/skills/planned/follow-up-generator',
  OS_SKILLS_PLANNED_GOOGLE_ADS_REVIEW: '/os/skills/planned/google-ads-review',
  OS_SKILLS_PLANNED_LANDING_PAGE_BUILDER:
    '/os/skills/planned/landing-page-builder',
  OS_SKILLS_PLANNED_LEAD_PRIORITIZER: '/os/skills/planned/lead-prioritizer',
  OS_SKILLS_PLANNED_META_ADS_REVIEW: '/os/skills/planned/meta-ads-review',
  OS_SKILLS_PLANNED_POST_CALL_ANALYSIS: '/os/skills/planned/post-call-analysis',
  OS_SKILLS_PLANNED_SALES_COACHING: '/os/skills/planned/sales-coaching',
  OS_SKILLS_PLANNED_WEEKLY_MANAGER_REPORT:
    '/os/skills/planned/weekly-manager-report',
  OS_SKILLS_RESEARCH_INGEST: '/os/skills/research-ingest',
  OS_SKILLS_SENIOR_ENGINEER: '/os/skills/senior-engineer',
  OS_SKILLS_SKILL_CREATOR: '/os/skills/skill-creator',
  OS_SKILLS_TASK: '/os/skills/task',
  OS_TOOLS_BROWSER_TOOLS: '/os/tools/browser-tools',
  OS_TOOLS_EXPLORATION_TOOLS: '/os/tools/exploration-tools',
  OS_TOOLS_FILESYSTEM_TOOLS: '/os/tools/filesystem-tools',
  OS_TOOLS_GITHUB_AND_REVIEW_TOOLS: '/os/tools/github-and-review-tools',
  OS_TOOLS_OVERVIEW: '/os/tools/overview',
  OS_TOOLS_TASK_AND_STREAM_TOOLS: '/os/tools/task-and-stream-tools',
  OS_TOOLS_TOOL_SEARCH: '/os/tools/tool-search',
  USER_GUIDE_AI_CAPABILITIES_AI_AGENTS: '/user-guide/ai/capabilities/ai-agents',
  USER_GUIDE_AI_CAPABILITIES_AI_CHATBOT:
    '/user-guide/ai/capabilities/ai-chatbot',
  USER_GUIDE_AI_CAPABILITIES_PERMISSIONS_ACCESS_CONTROL:
    '/user-guide/ai/capabilities/permissions-access-control',
  USER_GUIDE_AI_HOW_TOS_AI_FAQ: '/user-guide/ai/how-tos/ai-faq',
  USER_GUIDE_AI_OVERVIEW: '/user-guide/ai/overview',
  USER_GUIDE_BILLING_CAPABILITIES_PRICING_PLANS:
    '/user-guide/billing/capabilities/pricing-plans',
  USER_GUIDE_BILLING_CAPABILITIES_WORKFLOW_CREDITS:
    '/user-guide/billing/capabilities/workflow-credits',
  USER_GUIDE_BILLING_HOW_TOS_BILLING_FAQ:
    '/user-guide/billing/how-tos/billing-faq',
  USER_GUIDE_BILLING_OVERVIEW: '/user-guide/billing/overview',
  USER_GUIDE_CALENDAR_EMAILS_CAPABILITIES_CALENDAR:
    '/user-guide/calendar-emails/capabilities/calendar',
  USER_GUIDE_CALENDAR_EMAILS_CAPABILITIES_MAILBOX:
    '/user-guide/calendar-emails/capabilities/mailbox',
  USER_GUIDE_CALENDAR_EMAILS_HOW_TOS_CAN_I_BOOK_MEETINGS_FROM_CONSUELO:
    '/user-guide/calendar-emails/how-tos/can-i-book-meetings-from-consuelo',
  USER_GUIDE_CALENDAR_EMAILS_HOW_TOS_CAN_I_SEND_EMAILS_FROM_CONSUELO:
    '/user-guide/calendar-emails/how-tos/can-i-send-emails-from-consuelo',
  USER_GUIDE_CALENDAR_EMAILS_HOW_TOS_CAN_I_TRACK_EMAIL_ACTIVITY_ON_ALL_OBJECTS:
    '/user-guide/calendar-emails/how-tos/can-i-track-email-activity-on-all-objects',
  USER_GUIDE_CALENDAR_EMAILS_HOW_TOS_CONNECT_SEVERAL_MAILBOXES_PER_USER:
    '/user-guide/calendar-emails/how-tos/connect-several-mailboxes-per-user',
  USER_GUIDE_CALENDAR_EMAILS_HOW_TOS_I_DONT_SEE_EMAILS_ON_RECORDS:
    '/user-guide/calendar-emails/how-tos/i-dont-see-emails-on-records',
  USER_GUIDE_CALENDAR_EMAILS_HOW_TOS_LIMIT_EMAILS_IMPORTED:
    '/user-guide/calendar-emails/how-tos/limit-emails-imported',
  USER_GUIDE_CALENDAR_EMAILS_OVERVIEW: '/user-guide/calendar-emails/overview',
  USER_GUIDE_DASHBOARDS_CAPABILITIES_CHART_SETTINGS:
    '/user-guide/dashboards/capabilities/chart-settings',
  USER_GUIDE_DASHBOARDS_CAPABILITIES_DASHBOARDS:
    '/user-guide/dashboards/capabilities/dashboards',
  USER_GUIDE_DASHBOARDS_CAPABILITIES_WIDGETS:
    '/user-guide/dashboards/capabilities/widgets',
  USER_GUIDE_DASHBOARDS_HOW_TOS_DASHBOARDS_FAQ:
    '/user-guide/dashboards/how-tos/dashboards-faq',
  USER_GUIDE_DASHBOARDS_HOW_TOS_WIDGET_FAQ:
    '/user-guide/dashboards/how-tos/widget-faq',
  USER_GUIDE_DASHBOARDS_OVERVIEW: '/user-guide/dashboards/overview',
  USER_GUIDE_DATA_MIGRATION_CAPABILITIES_ERROR_HANDLING:
    '/user-guide/data-migration/capabilities/error-handling',
  USER_GUIDE_DATA_MIGRATION_CAPABILITIES_FIELD_MAPPING:
    '/user-guide/data-migration/capabilities/field-mapping',
  USER_GUIDE_DATA_MIGRATION_CAPABILITIES_FILE_FORMATS:
    '/user-guide/data-migration/capabilities/file-formats',
  USER_GUIDE_DATA_MIGRATION_CAPABILITIES_IMPORT_RELATIONS:
    '/user-guide/data-migration/capabilities/import-relations',
  USER_GUIDE_DATA_MIGRATION_CAPABILITIES_UNIQUENESS_CONSTRAINTS:
    '/user-guide/data-migration/capabilities/uniqueness-constraints',
  USER_GUIDE_DATA_MIGRATION_HOW_TOS_EXPORT_YOUR_DATA:
    '/user-guide/data-migration/how-tos/export-your-data',
  USER_GUIDE_DATA_MIGRATION_HOW_TOS_FIX_IMPORT_ERRORS:
    '/user-guide/data-migration/how-tos/fix-import-errors',
  USER_GUIDE_DATA_MIGRATION_HOW_TOS_IMPORT_COMPANIES_VIA_CSV:
    '/user-guide/data-migration/how-tos/import-companies-via-csv',
  USER_GUIDE_DATA_MIGRATION_HOW_TOS_IMPORT_CONTACTS_VIA_CSV:
    '/user-guide/data-migration/how-tos/import-contacts-via-csv',
  USER_GUIDE_DATA_MIGRATION_HOW_TOS_IMPORT_DATA_VIA_API:
    '/user-guide/data-migration/how-tos/import-data-via-api',
  USER_GUIDE_DATA_MIGRATION_HOW_TOS_IMPORT_RELATIONS_BETWEEN_OBJECTS_VIA_CSV:
    '/user-guide/data-migration/how-tos/import-relations-between-objects-via-csv',
  USER_GUIDE_DATA_MIGRATION_HOW_TOS_MIGRATING_FROM_OTHER_CRMS:
    '/user-guide/data-migration/how-tos/migrating-from-other-crms',
  USER_GUIDE_DATA_MIGRATION_HOW_TOS_MIGRATING_FROM_SELF_HOSTED_TO_CLOUD:
    '/user-guide/data-migration/how-tos/migrating-from-self-hosted-to-cloud',
  USER_GUIDE_DATA_MIGRATION_HOW_TOS_PREPARE_YOUR_CSV_FILES:
    '/user-guide/data-migration/how-tos/prepare-your-csv-files',
  USER_GUIDE_DATA_MIGRATION_HOW_TOS_UPDATE_EXISTING_RECORDS_VIA_IMPORT:
    '/user-guide/data-migration/how-tos/update-existing-records-via-import',
  USER_GUIDE_DATA_MIGRATION_HOW_TOS_UPLOAD_CSV_PROGRAMMATICALLY:
    '/user-guide/data-migration/how-tos/upload-csv-programmatically',
  USER_GUIDE_DATA_MIGRATION_OVERVIEW: '/user-guide/data-migration/overview',
  USER_GUIDE_DATA_MODEL_CAPABILITIES_FIELDS:
    '/user-guide/data-model/capabilities/fields',
  USER_GUIDE_DATA_MODEL_CAPABILITIES_OBJECTS:
    '/user-guide/data-model/capabilities/objects',
  USER_GUIDE_DATA_MODEL_CAPABILITIES_RELATION_FIELDS:
    '/user-guide/data-model/capabilities/relation-fields',
  USER_GUIDE_DATA_MODEL_HOW_TOS_CREATE_CUSTOM_FIELDS:
    '/user-guide/data-model/how-tos/create-custom-fields',
  USER_GUIDE_DATA_MODEL_HOW_TOS_CREATE_CUSTOM_OBJECTS:
    '/user-guide/data-model/how-tos/create-custom-objects',
  USER_GUIDE_DATA_MODEL_HOW_TOS_CREATE_MANY_TO_MANY_RELATIONS:
    '/user-guide/data-model/how-tos/create-many-to-many-relations',
  USER_GUIDE_DATA_MODEL_HOW_TOS_CREATE_RELATION_FIELDS:
    '/user-guide/data-model/how-tos/create-relation-fields',
  USER_GUIDE_DATA_MODEL_HOW_TOS_CUSTOMIZE_YOUR_DATA_MODEL:
    '/user-guide/data-model/how-tos/customize-your-data-model',
  USER_GUIDE_DATA_MODEL_HOW_TOS_DATA_MODEL_FAQ:
    '/user-guide/data-model/how-tos/data-model-faq',
  USER_GUIDE_DATA_MODEL_OVERVIEW: '/user-guide/data-model/overview',
  USER_GUIDE_DIALER_HOLD_MUTE: '/user-guide/dialer/hold-mute',
  USER_GUIDE_DIALER_HOW_TOS_DISCORD_SETUP:
    '/user-guide/dialer/how-tos/discord-setup',
  USER_GUIDE_DIALER_MAKING_CALLS: '/user-guide/dialer/making-calls',
  USER_GUIDE_DIALER_OVERVIEW: '/user-guide/dialer/overview',
  USER_GUIDE_DIALER_TRANSFERS: '/user-guide/dialer/transfers',
  USER_GUIDE_DISCORD_BOT_CAPABILITIES_CALL_CONTROLS:
    '/user-guide/discord-bot/capabilities/call-controls',
  USER_GUIDE_DISCORD_BOT_CAPABILITIES_CONTACT_SEARCH:
    '/user-guide/discord-bot/capabilities/contact-search',
  USER_GUIDE_DISCORD_BOT_CAPABILITIES_QUEUE_MANAGEMENT:
    '/user-guide/discord-bot/capabilities/queue-management',
  USER_GUIDE_DISCORD_BOT_CAPABILITIES_TEAM_COLLABORATION:
    '/user-guide/discord-bot/capabilities/team-collaboration',
  USER_GUIDE_DISCORD_BOT_GETTING_STARTED:
    '/user-guide/discord-bot/getting-started',
  USER_GUIDE_DISCORD_BOT_OVERVIEW: '/user-guide/discord-bot/overview',
  USER_GUIDE_FILE_SYSTEM_CAPABILITIES_AUTO_INDEXING:
    '/user-guide/file-system/capabilities/auto-indexing',
  USER_GUIDE_FILE_SYSTEM_CAPABILITIES_FILE_CATEGORIES:
    '/user-guide/file-system/capabilities/file-categories',
  USER_GUIDE_FILE_SYSTEM_CAPABILITIES_KNOWLEDGE_BASE:
    '/user-guide/file-system/capabilities/knowledge-base',
  USER_GUIDE_FILE_SYSTEM_HOW_TOS_FILE_SYSTEM_FAQ:
    '/user-guide/file-system/how-tos/file-system-faq',
  USER_GUIDE_FILE_SYSTEM_OVERVIEW: '/user-guide/file-system/overview',
  USER_GUIDE_GETTING_STARTED_CAPABILITIES_GLOSSARY:
    '/user-guide/getting-started/capabilities/glossary',
  USER_GUIDE_GETTING_STARTED_CAPABILITIES_IMPLEMENTATION_SERVICES:
    '/user-guide/getting-started/capabilities/implementation-services',
  USER_GUIDE_GETTING_STARTED_CAPABILITIES_KEYBOARD_SHORTCUTS:
    '/user-guide/getting-started/capabilities/keyboard-shortcuts',
  USER_GUIDE_GETTING_STARTED_CAPABILITIES_WHAT_IS_CONSUELO:
    '/user-guide/getting-started/capabilities/what-is-consuelo',
  USER_GUIDE_GETTING_STARTED_HOW_TOS_CONFIGURE_YOUR_WORKSPACE:
    '/user-guide/getting-started/how-tos/configure-your-workspace',
  USER_GUIDE_GETTING_STARTED_HOW_TOS_CREATE_WORKSPACE:
    '/user-guide/getting-started/how-tos/create-workspace',
  USER_GUIDE_GETTING_STARTED_HOW_TOS_NAVIGATE_AROUND_CONSUELO:
    '/user-guide/getting-started/how-tos/navigate-around-consuelo',
  USER_GUIDE_INTRODUCTION: '/user-guide/introduction',
  USER_GUIDE_PERMISSIONS_ACCESS_CAPABILITIES_PERMISSIONS:
    '/user-guide/permissions-access/capabilities/permissions',
  USER_GUIDE_PERMISSIONS_ACCESS_CAPABILITIES_SSO_CONFIGURATION:
    '/user-guide/permissions-access/capabilities/sso-configuration',
  USER_GUIDE_PERMISSIONS_ACCESS_HOW_TOS_PERMISSIONS_FAQ:
    '/user-guide/permissions-access/how-tos/permissions-faq',
  USER_GUIDE_PERMISSIONS_ACCESS_OVERVIEW:
    '/user-guide/permissions-access/overview',
  USER_GUIDE_SETTINGS_CAPABILITIES_DOMAINS_SETTINGS:
    '/user-guide/settings/capabilities/domains-settings',
  USER_GUIDE_SETTINGS_CAPABILITIES_EXPERIENCE_SETTINGS:
    '/user-guide/settings/capabilities/experience-settings',
  USER_GUIDE_SETTINGS_CAPABILITIES_MEMBER_MANAGEMENT:
    '/user-guide/settings/capabilities/member-management',
  USER_GUIDE_SETTINGS_CAPABILITIES_PROFILE_SETTINGS:
    '/user-guide/settings/capabilities/profile-settings',
  USER_GUIDE_SETTINGS_CAPABILITIES_UPDATES_SETTINGS:
    '/user-guide/settings/capabilities/updates-settings',
  USER_GUIDE_SETTINGS_CAPABILITIES_WORKSPACE_SETTINGS:
    '/user-guide/settings/capabilities/workspace-settings',
  USER_GUIDE_SETTINGS_HOW_TOS_SETTINGS_FAQ:
    '/user-guide/settings/how-tos/settings-faq',
  USER_GUIDE_SETTINGS_OVERVIEW: '/user-guide/settings/overview',
  USER_GUIDE_VIEWS_PIPELINES_CAPABILITIES_CALENDAR_VIEW:
    '/user-guide/views-pipelines/capabilities/calendar-view',
  USER_GUIDE_VIEWS_PIPELINES_CAPABILITIES_FIELDS_AND_COLUMNS:
    '/user-guide/views-pipelines/capabilities/fields-and-columns',
  USER_GUIDE_VIEWS_PIPELINES_CAPABILITIES_FILTERS_AND_SORTING:
    '/user-guide/views-pipelines/capabilities/filters-and-sorting',
  USER_GUIDE_VIEWS_PIPELINES_CAPABILITIES_KANBAN_VIEWS:
    '/user-guide/views-pipelines/capabilities/kanban-views',
  USER_GUIDE_VIEWS_PIPELINES_CAPABILITIES_TABLE_VIEWS:
    '/user-guide/views-pipelines/capabilities/table-views',
  USER_GUIDE_VIEWS_PIPELINES_CAPABILITIES_VIEW_SETTINGS:
    '/user-guide/views-pipelines/capabilities/view-settings',
  USER_GUIDE_VIEWS_PIPELINES_HOW_TOS_CREATE_A_CALENDAR_VIEW_FOR_TASKS_DUE:
    '/user-guide/views-pipelines/how-tos/create-a-calendar-view-for-tasks-due',
  USER_GUIDE_VIEWS_PIPELINES_HOW_TOS_CREATE_A_KANBAN_VIEW_FOR_PROJECTS:
    '/user-guide/views-pipelines/how-tos/create-a-kanban-view-for-projects',
  USER_GUIDE_VIEWS_PIPELINES_HOW_TOS_CREATE_A_TABLE_VIEW_WITH_GROUPING:
    '/user-guide/views-pipelines/how-tos/create-a-table-view-with-grouping',
  USER_GUIDE_VIEWS_PIPELINES_HOW_TOS_RESTRICT_ACCESS_TO_YOUR_VIEW:
    '/user-guide/views-pipelines/how-tos/restrict-access-to-your-view',
  USER_GUIDE_VIEWS_PIPELINES_HOW_TOS_SET_UP_A_SALES_PIPELINE:
    '/user-guide/views-pipelines/how-tos/set-up-a-sales-pipeline',
  USER_GUIDE_VIEWS_PIPELINES_HOW_TOS_SHOW_EXPECTED_AMOUNT_IN_PIPELINE:
    '/user-guide/views-pipelines/how-tos/show-expected-amount-in-pipeline',
  USER_GUIDE_VIEWS_PIPELINES_HOW_TOS_TRACK_TIME_IN_STAGE:
    '/user-guide/views-pipelines/how-tos/track-time-in-stage',
  USER_GUIDE_VIEWS_PIPELINES_OVERVIEW: '/user-guide/views-pipelines/overview',
  USER_GUIDE_WORKFLOWS_CAPABILITIES_SEND_EMAILS_FROM_WORKFLOWS:
    '/user-guide/workflows/capabilities/send-emails-from-workflows',
  USER_GUIDE_WORKFLOWS_CAPABILITIES_USE_BRANCHES_IN_WORKFLOWS:
    '/user-guide/workflows/capabilities/use-branches-in-workflows',
  USER_GUIDE_WORKFLOWS_CAPABILITIES_USE_ITERATOR:
    '/user-guide/workflows/capabilities/use-iterator',
  USER_GUIDE_WORKFLOWS_CAPABILITIES_WORKFLOW_ACTIONS:
    '/user-guide/workflows/capabilities/workflow-actions',
  USER_GUIDE_WORKFLOWS_CAPABILITIES_WORKFLOW_BRANCHES:
    '/user-guide/workflows/capabilities/workflow-branches',
  USER_GUIDE_WORKFLOWS_CAPABILITIES_WORKFLOW_CREDITS:
    '/user-guide/workflows/capabilities/workflow-credits',
  USER_GUIDE_WORKFLOWS_CAPABILITIES_WORKFLOW_RUNS:
    '/user-guide/workflows/capabilities/workflow-runs',
  USER_GUIDE_WORKFLOWS_CAPABILITIES_WORKFLOW_TRIGGERS:
    '/user-guide/workflows/capabilities/workflow-triggers',
  USER_GUIDE_WORKFLOWS_CAPABILITIES_WORKFLOW_VERSIONS:
    '/user-guide/workflows/capabilities/workflow-versions',
  USER_GUIDE_WORKFLOWS_HOW_TOS_ADVANCED_CONFIGURATIONS_HANDLE_ARRAYS_IN_CODE_ACTIONS:
    '/user-guide/workflows/how-tos/advanced-configurations/handle-arrays-in-code-actions',
  USER_GUIDE_WORKFLOWS_HOW_TOS_CONNECT_TO_OTHER_TOOLS_BRING_PRODUCT_DATA_IN_CONSUELO:
    '/user-guide/workflows/how-tos/connect-to-other-tools/bring-product-data-in-consuelo',
  USER_GUIDE_WORKFLOWS_HOW_TOS_CONNECT_TO_OTHER_TOOLS_BRING_TYPEFORM_SUBMISSIONS_IN_CONSUELO:
    '/user-guide/workflows/how-tos/connect-to-other-tools/bring-typeform-submissions-in-consuelo',
  USER_GUIDE_WORKFLOWS_HOW_TOS_CONNECT_TO_OTHER_TOOLS_GENERATE_PDF_FROM_CONSUELO:
    '/user-guide/workflows/how-tos/connect-to-other-tools/generate-pdf-from-consuelo',
  USER_GUIDE_WORKFLOWS_HOW_TOS_CONNECT_TO_OTHER_TOOLS_GENERATE_QUOTE_OR_INVOICE_FROM_CONSUELO:
    '/user-guide/workflows/how-tos/connect-to-other-tools/generate-quote-or-invoice-from-consuelo',
  USER_GUIDE_WORKFLOWS_HOW_TOS_CONNECT_TO_OTHER_TOOLS_SET_UP_A_WEBHOOK_TRIGGER:
    '/user-guide/workflows/how-tos/connect-to-other-tools/set-up-a-webhook-trigger',
  USER_GUIDE_WORKFLOWS_HOW_TOS_CRM_AUTOMATIONS_CLOSED_WON_AUTOMATIONS:
    '/user-guide/workflows/how-tos/crm-automations/closed-won-automations',
  USER_GUIDE_WORKFLOWS_HOW_TOS_CRM_AUTOMATIONS_DETECT_STALE_OPPORTUNITIES:
    '/user-guide/workflows/how-tos/crm-automations/detect-stale-opportunities',
  USER_GUIDE_WORKFLOWS_HOW_TOS_CRM_AUTOMATIONS_DISPLAY_NUMBER_OF_EMAILS_RECEIVED:
    '/user-guide/workflows/how-tos/crm-automations/display-number-of-emails-received',
  USER_GUIDE_WORKFLOWS_HOW_TOS_CRM_AUTOMATIONS_DISPLAY_RELATED_RECORD_DATA:
    '/user-guide/workflows/how-tos/crm-automations/display-related-record-data',
  USER_GUIDE_WORKFLOWS_HOW_TOS_CRM_AUTOMATIONS_FORMULA_FIELDS:
    '/user-guide/workflows/how-tos/crm-automations/formula-fields',
  USER_GUIDE_WORKFLOWS_HOW_TOS_CRM_AUTOMATIONS_NOTIFY_TEAMMATES_OF_NOTE_TO_REVIEW:
    '/user-guide/workflows/how-tos/crm-automations/notify-teammates-of-note-to-review',
  USER_GUIDE_WORKFLOWS_HOW_TOS_CRM_AUTOMATIONS_SEND_EMAIL_ALERTS_WITH_TASKS_DUE:
    '/user-guide/workflows/how-tos/crm-automations/send-email-alerts-with-tasks-due',
  USER_GUIDE_WORKFLOWS_HOW_TOS_NEED_MORE_HELP_PROFESSIONAL_SERVICES:
    '/user-guide/workflows/how-tos/need-more-help/professional-services',
  USER_GUIDE_WORKFLOWS_HOW_TOS_NEED_MORE_HELP_WORKFLOW_TROUBLESHOOTING:
    '/user-guide/workflows/how-tos/need-more-help/workflow-troubleshooting',
  USER_GUIDE_WORKFLOWS_HOW_TOS_NEED_MORE_HELP_WORKFLOWS_FAQ:
    '/user-guide/workflows/how-tos/need-more-help/workflows-faq',
  USER_GUIDE_WORKFLOWS_OVERVIEW: '/user-guide/workflows/overview',
} as const;

export type DocumentationPath =
  (typeof DOCUMENTATION_PATHS)[keyof typeof DOCUMENTATION_PATHS];
