export const LOCAL_OS_ROUTE_POLICIES = [
  { method: 'ANY', path: '/health', trust: 'public' },
  { method: 'GET', path: '/artifacts', trust: 'public' },
  { method: 'GET', path: '/artifacts/*', trust: 'public' },
  { method: 'GET', path: '/gateway/artifacts', trust: 'signed' },
  { method: 'GET', path: '/gateway/artifacts/:artifactId', trust: 'signed' },
  { method: 'GET', path: '/gateway/artifacts/:artifactId/versions', trust: 'signed' },
  { method: 'GET', path: '/gateway/traces/recent', trust: 'signed' },
  { method: 'GET', path: '/gateway/traces/summary', trust: 'signed' },
  { method: 'GET', path: '/gateway/traces/aggregates', trust: 'signed' },
  { method: 'GET', path: '/gateway/traces/events', trust: 'signed' },
  { method: 'GET', path: '/gateway/configuration/snapshot', trust: 'signed' },
  { method: 'POST', path: '/gateway/configuration/overlay', trust: 'signed' },
  { method: 'GET', path: '/gateway/settings/snapshot', trust: 'signed' },
  { method: 'POST', path: '/gateway/settings/overlay', trust: 'signed' },
  { method: 'ANY', path: '/mcp', trust: 'signed-or-oauth' },
  { method: 'GET', path: '/get_steering', trust: 'signed' },
  { method: 'POST', path: '/get_steering', trust: 'signed' },
  { method: 'POST', path: '/call', trust: 'signed' },
  { method: 'ANY', path: '*', trust: 'signed-fallback' },
] as const;
