export const TOOL_PERMISSION_FLAGS = [
  'AI',
  'VIEWS',
  'UPLOAD_FILE',
  'DOWNLOAD_FILE',
  'SEND_EMAIL_TOOL',
  'DIALER_CALLING',
  'HTTP_REQUEST_TOOL',
  'IMPORT_CSV',
  'EXPORT_CSV',
  'CONNECTED_ACCOUNTS',
  'PROFILE_INFORMATION',
  'CODE_INTERPRETER_TOOL',
];
