import fs from 'node:fs';
import path from 'node:path';

import {
  getArtifactByPath,
  publishArtifact,
  resolveArtifactCurrentIndex,
} from '../lib/artifacts';
import { resolveConsueloHome } from '../lib/consuelo-home';
import { proveGraphQLConnectivity } from '../lib/graphql-client';
import type { ArtifactDescriptor, CallOutput, SkillContext } from '../lib/types';

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function renderRevenueBrief(input: {
  generatedAt: string;
  traceId: string;
  skillName: string;
  result: Record<string, unknown>;
}): string {
  const resultJson = escapeHtml(JSON.stringify(input.result, null, 2));
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Daily Revenue Brief · Consuelo Artifacts</title>
  <meta name="description" content="Daily revenue brief generated by Consuelo OS." />
  <style>
    :root { color-scheme: light dark; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; }
    body { max-width: 860px; margin: 0 auto; padding: 48px 24px; line-height: 1.55; }
    header { border-bottom: 1px solid currentColor; padding-bottom: 24px; margin-bottom: 32px; }
    h1 { margin: 0 0 10px; }
    p { opacity: .75; }
    pre { overflow: auto; padding: 20px; border: 1px solid currentColor; border-radius: 12px; }
  </style>
</head>
<body>
  <header>
    <p><a href="/artifacts">Consuelo Artifacts</a></p>
    <h1>Daily Revenue Brief</h1>
    <p>Generated ${escapeHtml(input.generatedAt)} · Trace ${escapeHtml(input.traceId)}</p>
  </header>
  <pre>${resultJson}</pre>
</body>
</html>`;
}

export async function runDailyRevenueBrief(input: unknown, context: SkillContext): Promise<CallOutput> {
  let graphqlProof: Awaited<ReturnType<typeof proveGraphQLConnectivity>>;
  try {
    graphqlProof = await proveGraphQLConnectivity();
  } catch (error: unknown) {
    graphqlProof = {
      status: 'query_failed' as const,
      hasApiKey: Boolean(process.env.CONSUELO_INTERNAL_GRAPHQL_API_KEY),
      safeMessage: error instanceof Error ? error.message.slice(0, 240) : 'GraphQL proof failed.',
    };
  }
  const workspaceStatus = context.workspaceId
    ? 'workspace_configured'
    : 'workspace_not_provided';

  const result = {
    summary: 'Daily revenue brief scaffold executed.',
    workspaceStatus,
    graphqlStatus: graphqlProof.status,
    graphql: {
      urlHost: graphqlProof.urlHost,
      hasApiKey: graphqlProof.hasApiKey,
      safeMessage: graphqlProof.safeMessage,
    },
    receivedInput: input,
    nextSteps: [
      'Wire real call analytics',
      'Wire lead prioritization',
      'Replace scaffold data with production revenue signals',
    ],
  };

  const home = resolveConsueloHome();
  const routePath = '/revenue/daily-revenue-brief';
  const generatedAt = new Date().toISOString();
  const temporaryDir = path.join(home, 'node', 'tmp');
  const temporaryPath = path.join(temporaryDir, `daily-revenue-brief-${context.traceId}.html`);
  fs.mkdirSync(temporaryDir, { recursive: true });
  fs.writeFileSync(temporaryPath, renderRevenueBrief({
    generatedAt,
    traceId: context.traceId,
    skillName: context.manifestEntry.name,
    result,
  }), { mode: 0o600 });

  try {
    const existing = getArtifactByPath(home, routePath);
    const published = publishArtifact({
      home,
      target: temporaryPath,
      path: routePath,
      title: 'Daily Revenue Brief',
      category: 'revenue',
      template: 'guide',
      baseVersion: existing?.currentVersionId,
      traceId: context.traceId,
      skillName: context.manifestEntry.name,
      reason: existing ? 'daily revenue brief refresh' : 'daily revenue brief create',
      now: generatedAt,
    });
    const currentIndex = resolveArtifactCurrentIndex(home, routePath);
    const artifact: ArtifactDescriptor = {
      id: published.artifact.id,
      name: 'index.html',
      title: published.artifact.title,
      path: `/artifacts${published.artifact.path}`,
      localPath: currentIndex,
      url: `/artifacts${published.artifact.path}`,
      storageKey: path.relative(home, currentIndex).split(path.sep).join('/'),
      type: 'report',
      format: 'html',
      status: 'published',
      storageMode: 'local',
      traceId: context.traceId,
      skillName: context.manifestEntry.name,
      createdAt: published.artifact.createdAt,
      currentVersionId: published.artifact.currentVersionId,
      versionCount: published.artifact.versionCount,
    };

    return {
      ok: true,
      name: context.manifestEntry.name,
      permission: context.manifestEntry.permission,
      requiresApproval: context.manifestEntry.requiresApproval,
      result,
      artifacts: [artifact],
      proposedWrites: [],
    };
  } finally {
    fs.rmSync(temporaryPath, { force: true });
  }
}
