import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const repoRoot = resolve(import.meta.dirname, '../../..');

const readRepoFile = (path: string) =>
  readFileSync(resolve(repoRoot, path), 'utf8');

const collectSourceFiles = (directory: string): string[] => {
  const absoluteDirectory = resolve(repoRoot, directory);

  if (!existsSync(absoluteDirectory)) {
    return [];
  }

  return readdirSync(absoluteDirectory).flatMap((entry) => {
    const absolutePath = resolve(absoluteDirectory, entry);
    const relativePath = `${directory}/${entry}`;

    if (statSync(absolutePath).isDirectory()) {
      return collectSourceFiles(relativePath);
    }

    return /\.(?:ts|tsx|js|jsx)$/.test(entry) ? [relativePath] : [];
  });
};

describe('twenty-emails package removal', () => {
  it('removes the deleted workspace from the package graph', () => {
    const rootPackage = readRepoFile('package.json');
    const serverPackage = readRepoFile('packages/twenty-server/package.json');
    const lockfile = readRepoFile('yarn.lock');

    expect(existsSync(resolve(repoRoot, 'packages/twenty-emails'))).toBe(false);
    expect(rootPackage).not.toContain('packages/twenty-emails');
    expect(serverPackage).not.toContain('"twenty-emails"');
    expect(lockfile).not.toContain('twenty-emails@workspace');
  });

  it('keeps the required email API inside twenty-server', () => {
    const serverSources = collectSourceFiles('packages/twenty-server/src');
    const staleImports = serverSources.filter((path) =>
      readRepoFile(path).includes("from 'twenty-emails'"),
    );
    const emailApi = readRepoFile(
      'packages/twenty-server/src/engine/core-modules/email/templates/index.ts',
    );

    expect(staleImports).toEqual([]);
    expect(emailApi).toContain('CleanSuspendedWorkspaceEmail');
    expect(emailApi).toContain('PasswordResetLinkEmail');
    expect(emailApi).toContain('PasswordUpdateNotifyEmail');
    expect(emailApi).toContain('SendEmailVerificationLinkEmail');
    expect(emailApi).toContain('SendInviteLinkEmail');
    expect(emailApi).toContain('SendApprovedAccessDomainValidation');
    expect(emailApi).toContain('WarnSuspendedWorkspaceEmail');
    expect(emailApi).toContain('reactMarkupFromJSON');
    expect(emailApi).toContain('JSONContent');
  });

  it('keeps email translations owned and generated by twenty-server', () => {
    const emailLinguiConfig = readRepoFile(
      'packages/twenty-server/lingui.email-templates.config.ts',
    );
    const serverLinguiConfig = readRepoFile(
      'packages/twenty-server/lingui.config.ts',
    );
    const serverProject = readRepoFile('packages/twenty-server/project.json');
    const frenchCatalog = readRepoFile(
      'packages/twenty-server/src/engine/core-modules/email/templates/locales/fr-FR.po',
    );

    expect(emailLinguiConfig).toContain(
      'src/engine/core-modules/email/templates/locales/{locale}',
    );
    expect(serverLinguiConfig).toContain(
      "exclude: ['src/engine/core-modules/email/templates/**']",
    );
    expect(serverProject).toContain('lingui.email-templates.config.ts');
    expect(frenchCatalog).toContain('Réinitialisez votre mot de passe');

    const localeDirectory = resolve(
      repoRoot,
      'packages/twenty-server/src/engine/core-modules/email/templates/locales',
    );
    const staleCatalogMetadata = readdirSync(localeDirectory)
      .filter((file) => file.endsWith('.po'))
      .filter((file) =>
        readFileSync(resolve(localeDirectory, file), 'utf8').includes(
          'packages/twenty-emails',
        ),
      );

    expect(staleCatalogMetadata).toEqual([]);
  });

  it('removes the deleted package from CI, containers, translations, and test discovery', () => {
    const infrastructureFiles = [
      'packages/twenty-docker/twenty/Dockerfile',
      'packages/twenty-docker/twenty/Dockerfile.worker',
      '.github/workflows/ci-server.yaml',
      '.github/crowdin-app.yml',
    ];

    expect(
      existsSync(resolve(repoRoot, '.github/workflows/ci-emails.yaml')),
    ).toBe(false);

    for (const file of infrastructureFiles) {
      expect(readRepoFile(file), file).not.toContain('twenty-emails');
    }

    const composeWorkflow = readRepoFile(
      '.github/workflows/ci-test-docker-compose.yaml',
    );

    expect(composeWorkflow).toContain('del(.services.worker.image)');
    expect(composeWorkflow).toContain(
      '.services.worker.build.dockerfile = "./packages/twenty-docker/twenty/Dockerfile.worker"',
    );

    const registry = JSON.parse(
      readRepoFile('packages/workspace/test-selection.registry.json'),
    ) as {
      projects: Array<{ name: string; root: string; file: string }>;
      packageScripts: Array<{ name: string; root: string; file: string }>;
    };
    const staleRegistryEntries = [
      ...registry.projects,
      ...registry.packageScripts,
    ].filter((entry) =>
      [entry.name, entry.root, entry.file].some((value) =>
        value.includes('twenty-emails'),
      ),
    );

    expect(staleRegistryEntries).toEqual([]);
  });

  it('keeps every workspace CLI bin target installable from a clean checkout', () => {
    const rootPackage = JSON.parse(readRepoFile('package.json')) as {
      workspaces: { packages: string[] };
    };
    const missingBinTargets: string[] = [];

    for (const workspace of rootPackage.workspaces.packages) {
      const manifestPath = resolve(repoRoot, workspace, 'package.json');
      if (!existsSync(manifestPath)) {
        continue;
      }

      const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as {
        name?: string;
        bin?: string | Record<string, string>;
      };
      const bins =
        typeof manifest.bin === 'string'
          ? { [manifest.name ?? workspace]: manifest.bin }
          : (manifest.bin ?? {});

      for (const [name, target] of Object.entries(bins)) {
        const binPath = resolve(repoRoot, workspace, target);
        if (!existsSync(binPath)) {
          missingBinTargets.push(`${name}: ${workspace}/${target}`);
        }
      }
    }

    expect(missingBinTargets).toEqual([]);
  });
});
