import { classifyTaskCommand } from './command-quality';
import { compactText, sanitizeRecord, stripWrapperInternals } from './sanitize';
import type { NormalizedTraceRow, TraceChild, TraceHomeBuildOptions, TraceHomeModel, TraceHomeRow } from './types';

type JsonRecord = Record<string, unknown>;
export function parseJson(value: unknown): unknown { if (typeof value !== 'string' || !value.trim()) return undefined; try { return JSON.parse(value); } catch { return undefined; } }
function isRecord(value: unknown): value is JsonRecord { return value !== null && typeof value === 'object' && !Array.isArray(value); }
function cleanText(value: unknown): string { return stripWrapperInternals(String(value ?? '')).trim().replace(/\s+/g, ' '); }
export function numeric(value: unknown, fallback = 0): number { const n = Number(value ?? fallback); return Number.isFinite(n) ? n : fallback; }
const localTimestampFormatter = new Intl.DateTimeFormat('en-US', {
  year: 'numeric',
  month: '2-digit',
  day: '2-digit',
  hour: '2-digit',
  minute: '2-digit',
  second: '2-digit',
  hour12: false,
});

function localTimestampParts(date: Date): Record<string, string> {
  return Object.fromEntries(localTimestampFormatter.formatToParts(date).map((part) => [part.type, part.value])) as Record<string, string>;
}

export function formatTime(value: unknown): string {
  const date = new Date(String(value || ''));
  if (Number.isNaN(date.getTime())) return '---- -- -- --:--:--';
  const parts = localTimestampParts(date);
  return `${parts.year}-${parts.month}-${parts.day} ${parts.hour === '24' ? '00' : parts.hour}:${parts.minute}:${parts.second}`;
}
export function formatDuration(ms: unknown): string { const d = numeric(ms, 0); return d >= 1000 ? `${(d / 1000).toFixed(2)}s` : `${Math.round(d)}ms`; }
export function formatTokens(value: unknown): string { const t = numeric(value, 0); if (t >= 1_000_000) return `${(t / 1_000_000).toFixed(1)}m`; if (t >= 1000) return `${(t / 1000).toFixed(1)}k`; return String(Math.round(t)); }
function shortBranch(value: unknown): string { return cleanText(value || 'no-branch').replace(/^task\//, '').replace(/^stream\//, 'stream/'); }
function commandFromRow(row: TraceHomeRow): string[] { const input = parseJson(row.resolved_input_json) ?? parseJson(row.input_json); if (isRecord(input) && Array.isArray(input.command)) return input.command.map(String); if (isRecord(input) && Array.isArray(input.args)) return input.args.map(String); return []; }
function isOk(row: TraceHomeRow): boolean { return String(row.status || '') === 'ok' && String(row.code || '') === 'OK' && numeric(row.exit_code, 0) === 0; }
function asArray(value: unknown): unknown[] { return Array.isArray(value) ? value : []; }
function childFrom(result: unknown, fallback: string): TraceChild | undefined { if (!isRecord(result)) return undefined; const ok = result.ok === true || (result.code === 'OK' && result.ok !== false); return { tool: cleanText(result.tool || fallback || 'unknown') || 'unknown', ok, status: ok ? 'ok' : cleanText(result.code || 'ERR'), durationMs: numeric(result.durationMs ?? result.duration_ms, 0), totalTokens: numeric(result.totalTokens ?? result.total_tokens, 0), detail: compactText(result.detail || result.message || '', 160) }; }
function codeRunChildren(row: TraceHomeRow): TraceChild[] { const extracted = parseJson(row.nested_operations_json); const result = parseJson(row.result_json); const data = isRecord(result) && isRecord(result.data) ? result.data : undefined; const nestedData = data && isRecord(data.data) ? data.data : undefined; return asArray(extracted ?? data?.operations ?? nestedData?.operations).map((op) => childFrom(op, 'unknown')).filter(Boolean) as TraceChild[]; }
function batchChildren(row: TraceHomeRow): TraceChild[] { const input = parseJson(row.resolved_input_json) ?? parseJson(row.input_json) ?? {}; const steps = Array.isArray(input) ? input : isRecord(input) ? asArray(input.steps) : []; const extracted = parseJson(row.batch_results_json); const result = parseJson(row.result_json); const data = isRecord(result) && isRecord(result.data) ? result.data : undefined; const nestedData = data && isRecord(data.data) ? data.data : undefined; return asArray(extracted ?? data?.results ?? nestedData?.results).map((r, i) => childFrom(r, isRecord(steps[i]) ? cleanText(steps[i].tool) : 'unknown')).filter(Boolean) as TraceChild[]; }
function childrenForRow(row: TraceHomeRow): TraceChild[] { if (row.tool === 'code.run') return codeRunChildren(row); if (row.tool === 'batch') return batchChildren(row); return []; }
function messageForRow(row: TraceHomeRow, command: string[]): string { const all = `${row.stderr || ''}\n${row.result_json || ''}`; const marker = 'execFile' + 'Sync'; if (all.includes(marker) || /gh\s+run\s+view|github/i.test(all)) return 'github raw failed · reason: GitHub job is still in progress; logs are unavailable yet · command: gh run view ...'; if (command.length) return compactText(command.join(' '), 240); const result = parseJson(row.result_json); if (isRecord(result)) { if (result.message) return compactText(result.message, 240); if (isRecord(result.data) && result.data.message) return compactText(result.data.message, 240); } return cleanText(row.code || row.status || ''); }
function normalizeRow(row: TraceHomeRow, rawJson = false): NormalizedTraceRow { const command = commandFromRow(row); const ok = isOk(row); const children = childrenForRow(row); const tool = cleanText(row.tool || 'unknown'); const commandQuality = undefined; const childTokens = children.reduce((sum, child) => sum + child.totalTokens, 0); const branch = cleanText(row.branch || row.task_session || 'no-branch'); const rawWithClassification = { ...row, classification: commandQuality }; return { id: cleanText(row.record_id || row.trace_id || row.rownum || ''), rownum: numeric(row.rownum, 0), time: formatTime(row.ts), timestampMs: new Date(String(row.ts || '')).getTime() || 0, traceId: cleanText(row.trace_id), tool, status: cleanText(row.status || (ok ? 'ok' : 'failed')), ok, code: cleanText(row.code || (ok ? 'OK' : 'ERR')), durationMs: numeric(row.duration_ms, 0), inputTokens: numeric(row.input_tokens, 0), outputTokens: numeric(row.output_tokens, 0), totalTokens: numeric(row.total_tokens, 0) || childTokens, branch, shortBranch: shortBranch(branch), command: compactText(command.join(' '), 400), message: messageForRow(row, command), stderr: compactText(row.stderr, 500), raw: row, children, commandQuality, sanitizedRaw: sanitizeRecord(rawWithClassification, rawJson) }; }
function filterRows(rows: NormalizedTraceRow[], options: TraceHomeBuildOptions): NormalizedTraceRow[] { const search = (options.search || '').toLowerCase().trim(); return rows.filter((row) => { if (options.failedOnly && row.ok) return false; if (options.branchFilter && row.branch !== options.branchFilter && row.shortBranch !== options.branchFilter) return false; if (options.toolFilter && row.tool !== options.toolFilter) return false; if (search && !`${row.tool} ${row.branch} ${row.shortBranch} ${row.message} ${row.command} ${row.traceId}`.toLowerCase().includes(search)) return false; return true; }); }
function inspect(row: NormalizedTraceRow): TraceHomeModel['inspect'] { const provider = Math.max(0, row.durationMs - 5); return { traceId: row.traceId, status: row.ok ? 'ok' : 'failed', duration: `${formatDuration(row.durationMs)} wall`, tokens: `${row.totalTokens} total · input ${row.inputTokens} · output ${row.outputTokens}`, branch: row.shortBranch, timing: `wall ${formatDuration(row.durationMs)} · provider ${formatDuration(provider)} derived · emit unavailable`, command: row.command || row.message, stdout: '', stderr: row.stderr, commandQuality: row.commandQuality, tabs: ['COMMAND', 'STDOUT', 'STDERR', 'JSON', `CHILDREN (${row.children.length})`, 'METRICS'] }; }
function treeLines(rows: NormalizedTraceRow[], selected?: NormalizedTraceRow): string[] { const lines: string[] = []; for (const row of rows) { lines.push(`${row.traceId === selected?.traceId ? '▸' : ' '} ${row.ok ? '✓' : '✕'} ${row.tool} ${formatDuration(row.durationMs)} ${row.shortBranch}`.trimEnd()); for (const child of row.children) lines.push(`  ├─ ${child.ok ? '✓' : '✕'} ${child.tool} ${formatDuration(child.durationMs)} ${child.detail}`.trimEnd()); } return lines; }
export function buildTraceHomeModel(rows: TraceHomeRow[], options: TraceHomeBuildOptions = {}): TraceHomeModel { const normalized = [...rows].sort((a, b) => numeric(a.rownum, 0) - numeric(b.rownum, 0)).map((row) => normalizeRow(row, options.rawJson)); const visibleRows = filterRows(normalized, options); const errors = normalized.filter((row) => !row.ok).length; const running = normalized.filter((row) => row.status === 'running' || row.status === 'pending').length; const branches = new Set(normalized.map((row) => row.branch)).size; const selectedRowIndex = Math.min(Math.max(options.selectedIndex ?? 0, 0), Math.max(visibleRows.length - 1, 0)); const selected = (options.selectedTraceId ? visibleRows.find((row) => row.traceId === options.selectedTraceId) : undefined) ?? visibleRows[selectedRowIndex] ?? normalized[0]; const selectedIndex = selected ? Math.max(0, visibleRows.findIndex((row) => row.traceId === selected.traceId)) : 0; const toolAggregation = new Map<string, { tool: string; tokens: number; calls: number }>(); for (const row of normalized) { const current = toolAggregation.get(row.tool) ?? { tool: row.tool, tokens: 0, calls: 0 }; current.tokens += row.totalTokens; current.calls += 1; toolAggregation.set(row.tool, current); } const rawShell = { total: 0, good: 0, suspect: 0, bad: 0 }; for (const row of normalized) if (row.commandQuality) { rawShell.total += 1; rawShell[row.commandQuality.quality] += 1; } const filter = [options.failedOnly ? 'failed' : '', options.search ? `search:${options.search}` : '', options.branchFilter ? `branch:${options.branchFilter}` : '', options.toolFilter ? `tool:${options.toolFilter}` : ''].filter(Boolean).join(' ') || 'none'; return { header: { title: 'trace:home', live: options.live !== false, rows: normalized.length, errors, running, branches, since: options.sinceLabel || 'now', filter, group: options.group || 'none' }, rows: normalized, visibleRows, summary: { rows: normalized.length, errors, running, branches, since: options.sinceLabel || 'now' }, topTools: [...toolAggregation.values()].sort((a, b) => b.tokens - a.tokens || b.calls - a.calls).slice(0, 8), rawShell, selectedIndex, selected, inspect: selected ? inspect(selected) : undefined, tree: { lines: treeLines(visibleRows, selected) }, rawJson: selected ? JSON.stringify(selected.sanitizedRaw, null, 2) : '{}' }; }
export type { TraceHomeBuildOptions, TraceHomeModel, TraceHomeRow } from './types';

